# Generated by Django 5.0.2 on 2024-02-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_authors_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors_public',
            name='first_name',
        ),
    ]
