# Generated by Django 5.0.2 on 2024-02-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_public_board_intersr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_board',
            old_name='intersr',
            new_name='interest',
        ),
    ]
