# Generated by Django 5.0.2 on 2024-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_relevance_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
