# Generated by Django 5.0.2 on 2024-02-28 19:12

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='public_board',
            managers=[
                ('athors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='relevance_board',
            managers=[
                ('man', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='public_board',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
