# Generated by Django 5.0.2 on 2024-02-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_public_board_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='public_board',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='relevance_board',
            managers=[
            ],
        ),
    ]
